# Generated by Django 4.2.5 on 2023-10-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moto', '0003_orderline_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_review', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='moto.partservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'ServiceReview',
                'verbose_name_plural': 'ServiceReviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
